# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms/cracker.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(370, 600)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Pairs = StrongBodyLabel(Form)
        self.Label_Pairs.setObjectName("Label_Pairs")
        self.horizontalLayout.addWidget(self.Label_Pairs)
        self.sBox_Pairs = SpinBox(Form)
        self.sBox_Pairs.setMinimum(1)
        self.sBox_Pairs.setObjectName("sBox_Pairs")
        self.horizontalLayout.addWidget(self.sBox_Pairs)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.TableWidget_Pairs = TableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget_Pairs.sizePolicy().hasHeightForWidth())
        self.TableWidget_Pairs.setSizePolicy(sizePolicy)
        self.TableWidget_Pairs.setShowGrid(False)
        self.TableWidget_Pairs.setGridStyle(QtCore.Qt.CustomDashLine)
        self.TableWidget_Pairs.setObjectName("TableWidget_Pairs")
        self.TableWidget_Pairs.setColumnCount(0)
        self.TableWidget_Pairs.setRowCount(0)
        self.verticalLayout.addWidget(self.TableWidget_Pairs)
        self.HorizontalSeparator = HorizontalSeparator(Form)
        self.HorizontalSeparator.setObjectName("HorizontalSeparator")
        self.verticalLayout.addWidget(self.HorizontalSeparator)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.ppBtn_Crack = PrimaryPushButton(Form)
        self.ppBtn_Crack.setObjectName("ppBtn_Crack")
        self.horizontalLayout_4.addWidget(self.ppBtn_Crack)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.IndeterminateProgressBar = IndeterminateProgressBar(Form)
        self.IndeterminateProgressBar.setObjectName("IndeterminateProgressBar")
        self.horizontalLayout_5.addWidget(self.IndeterminateProgressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.TableWidget_Keys = TableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget_Keys.sizePolicy().hasHeightForWidth())
        self.TableWidget_Keys.setSizePolicy(sizePolicy)
        self.TableWidget_Keys.setMinimumSize(QtCore.QSize(0, 200))
        self.TableWidget_Keys.setObjectName("TableWidget_Keys")
        self.TableWidget_Keys.setColumnCount(0)
        self.TableWidget_Keys.setRowCount(0)
        self.verticalLayout.addWidget(self.TableWidget_Keys)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cracker"))
        self.Label_Pairs.setText(_translate("Form", "明密文对数："))
        self.ppBtn_Crack.setText(_translate("Form", "开始暴力破解"))
from qfluentwidgets import HorizontalSeparator, IndeterminateProgressBar, PrimaryPushButton, SpinBox, StrongBodyLabel, TableWidget
